spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_test
    username: test_user
    password: test_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: WARN
    com.ascender.library: INFO
